input_dir = Path("input")
output_dir = Path("output")

landscape_resolution_str = "320x240"

threshold = 2.0

recursive = True
dry_run = False
rotatable_screen = True

img_exts = frozenset({".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"})

[blur]
output_dir = Path("output") / "blur"
radius = 2.0

[equidistant-crop]
output_dir = Path("output") / "equidistant_crop"
scale-factor = 0.5

[extreme-crop]
output_dir = Path("output") / "extreme_crop"
scale-factor = 1.0